import Head from "next/head";
import Banner from "../components/banner/Banner";
import SectionCards from "../components/card/SectionCards";
import Navbar from "../components/nav/Navbar";

import { verifyToken } from "../lib/utils";
import {
  getPopularVideos,
  getVideos,
  getWatchItAgainVideos,
} from "../lib/videos";
import styles from "../styles/Home.module.css";
import redirectUser from "../utils/redirectUser";

export default function Home(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>NetFlix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <Navbar userName="safin.ahmed2000@gmail.com" />
        <Banner
          videoId="mqqft2x_Aa4"
          title="The Batman"
          subTitle="Watch this exclusive clip of the opening scene of the The Batman where Gotham begins to learn the meaning of vengeance. The Batman is now streaming via HBO on HBO Max."
          imgUrl="https://i.ytimg.com/vi/mqqft2x_Aa4/maxresdefault.jpg"
        />

        <div className={styles.sectionWrapper}>
          <SectionCards title="DC" videos={props.dcVideos} size="large" />
          <SectionCards
            title="Watch it again"
            videos={props.watchItAgainVideos}
            size="small"
          />
          <SectionCards
            title="Marvel"
            videos={props.marvelVideos}
            size="small"
          />
          <SectionCards
            title="Gaming"
            videos={props.gamingVideos}
            size="medium"
          />
          <SectionCards
            title="Series"
            videos={props.netflixSeries}
            size="small"
          />
          <SectionCards
            title="Popular"
            videos={props.popularVideos}
            size="small"
          />
        </div>
      </div>

      {/* <Navbar />
      <Banner /> 

      <Card /> */}
    </div>
  );
}

export async function getServerSideProps(context) {
  const { userId, token } = await redirectUser(context);

  const watchItAgainVideos = await getWatchItAgainVideos(token, userId);
  const dcVideos = await getVideos("dc trailers");
  const marvelVideos = await getVideos("Marvel Trailers");
  const gamingVideos = await getVideos("Gaming Trailers");
  const netflixSeries = await getVideos("Netflix series trailers");
  const popularVideos = await getPopularVideos();
  return {
    props: {
      dcVideos,
      marvelVideos,
      gamingVideos,
      popularVideos,
      netflixSeries,
      watchItAgainVideos,
    },
  };
}
